"""add skill architecture

Revision ID: 08074a85dce1
Revises: 2fb2bd3ce775
Create Date: 2026-02-23 14:50:21.458309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08074a85dce1'
down_revision: Union[str, Sequence[str], None] = '2fb2bd3ce775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('normalized_name')
    )
    op.create_index(op.f('ix_skills_id'), 'skills', ['id'], unique=False)
    op.create_table('job_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'skill_id', name='unique_job_skill')
    )
    op.create_index(op.f('ix_job_skills_id'), 'job_skills', ['id'], unique=False)
    op.create_table('resume_skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resume_id', 'skill_id', name='unique_resume_skill')
    )
    op.create_index(op.f('ix_resume_skills_id'), 'resume_skills', ['id'], unique=False)
    op.alter_column('candidate_scores', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_unique_constraint('unique_job_resume_score', 'candidate_scores', ['job_id', 'resume_id'])
    op.drop_constraint(op.f('candidate_scores_job_id_fkey'), 'candidate_scores', type_='foreignkey')
    op.drop_constraint(op.f('candidate_scores_resume_id_fkey'), 'candidate_scores', type_='foreignkey')
    op.create_foreign_key(None, 'candidate_scores', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'candidate_scores', 'resumes', ['resume_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate_scores', type_='foreignkey')
    op.drop_constraint(None, 'candidate_scores', type_='foreignkey')
    op.create_foreign_key(op.f('candidate_scores_resume_id_fkey'), 'candidate_scores', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key(op.f('candidate_scores_job_id_fkey'), 'candidate_scores', 'jobs', ['job_id'], ['id'])
    op.drop_constraint('unique_job_resume_score', 'candidate_scores', type_='unique')
    op.alter_column('candidate_scores', 'job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_resume_skills_id'), table_name='resume_skills')
    op.drop_table('resume_skills')
    op.drop_index(op.f('ix_job_skills_id'), table_name='job_skills')
    op.drop_table('job_skills')
    op.drop_index(op.f('ix_skills_id'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
